trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod -- -op ..\..\dist
  displayName: 'npm install and build'

# Node.js with Angular
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise(0a0dfef5-3633-4c9f-86d0-989dec5df8db)'
    appType: 'webApp'
    WebAppName: 'JuridicoAeronaves'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/dist/'
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
